### ISSUE TITLE
VIDÉO PRÉSENTATION

### ISSUE THREAD

**Issue by AtlasRW** [metislab/pilea#2]
Vidéo de présentation de l'appli en production pour THP

- [x] Écriture
- [x] Capture Vidéo
- [x] Capture Voix
- [x] Montage Vidéo
- [x] Upload YouTube
- [x] Ajout lien au README

**Comment by gringer-and-granger** [comment]
6.3.2. Une vidéo de présentation
Afin de simplifier le process et de vous entraîner pour les présentations, nous vous demanderons de faire un vidéo YouTube pour introduire votre projet. Les présentations, au format vidéo, vont durer maxi 6 minutes.
Ces présentations feront office de "demo qui vend du rêve". Elles seront principalement orientées produit, et doivent absolument être présentées en production. Voici le format conseillé :

L'elevator pitch - 1 mn
Epatez le jury avec votre elevator pitch

La présentation globale
Présentation globale de votre solution, un coup d'oeil pour en savoir plus :

Comment fonctionne votre app ?
Montrez-nous LA fonctionnalité la plus importante de votre app
Pas besoin de nous montrer les fonctionnalités évidentes comme le signup / login : personne ne va utiliser votre app suite à une démo d'un branchement Devise ;)
Les features
Présentation de quelques features, celles dont vous êtes le plus fier, comme un algo de matchmaking, un système de réservation, un chat en AJAX, etc

Après THP
Parlez-nous de la suite : comment voyez vous le futur de cette application ? Quelles sont vos ambitions ?

**Comment by gringer-and-granger** [comment]
1/who
2/why
3/how
4/target
5/mission
6/interface site
7/utilisation
8/features
9/en quoi on repond a la problematique
10/futur

**Comment by gringer-and-granger** [comment]
1/who: l equipe pilea ,5devs interessés par la crypto
2/why on sest rendu compte probleme /montrer exemple CMC
3/how pilea plateforme/pas de superflus
4/target les gens de novice a confirmé qui veulent voir/suivre/surveiller
5/mission faire de l'investissement et la blockchain quelque chose de moins barbare
6/interface site presentation de la navigation
7/utilisation cliquer sur courbes, montrer simplicite (granularité)
8/features (mettre en favoris)
9/en quoi on repond a la problematique (on montre que bcp plus simple, pas de pub, lien sponso et facile a comprendre)
10/futur Cette interface servira d MVP a la suite du projet qui va continuer dans les bureaux de Nice

se délester du superflu/
dévelloper une équipe
avec passion

patience
